site_name: FlowMRI
repo_name: Evelyn92/FlowMRI
repo_url: https://github.com/Evelyn92/FlowMRI


nav:
    - Home: index.md
    - About me: nav/yiwei_cv.md
    - Artifacts: 
      - nav/getting-started.md
    - MRI Basics:
      - nav/setup/components.md
      - nav/setup/colors.md
      - nav/setup/fonts.md
      - nav/setup/logo.md
      - nav/setup/favicon.md
    - Sequences:
      - nav/development/development-guide.md
      - nav/development/release-notes.md

theme:
  name: simple-blog
  favicon: assets/favicon.ico
  logo: assets/logo.png
  theme_style: light
  site_name_style: normal
  title_style: bold
  colors:
    text: black
    title: black
    primary: black
    background: white
  components:
    site_name: true
    title: true
    menu: true
    preview: true
    footer: true