site_name: FlowMRI
repo_name: Evelyn92/FlowMRI
repo_url: https://github.com/Evelyn92/FlowMRI
site_url: https://evelyn92.github.io/FlowMRI


nav:
    - Home: index.md
    - About me: nav/yiwei_cv.md
    - Artifacts: 
      - bulk motion: nav/papers/adaptive_bulk_motion.md
      - head motion: nav/papers/retrospective_correction.md
      - SISMIK DL motion: SISMIK_for_brain_MRI.md

    - Sequences:
      - nav/
    - Thought wandering:
     - nav/random_thoughts.md

theme:
  name: simple-blog
  favicon: assets/favicon.ico
  logo: assets/logo.png
  theme_style: light
  site_name_style: normal
  title_style: normal
  colors:
    text: black
    title: black
    primary: black
    background: white
  components:
    site_name: true
    title: true
    menu: true
    preview: true
    footer: true

extra_css:
  - stylesheets/extra.css